food_dictionary = {
    "Poori": ["puri", "poori", "puris", "pooris", "phulka", "phulkas", "bhatura", "batura", "bhaturas", "baturas"],
    "Dosa": ["dosa", "dosai", "dosas", "dosais", "dose", "doses"],
    "Idli": ["idli", "idlis", "iddly", "iddlies", "italy"],
    "Vada": ["vada", "vadai", "vadas", "vadais", "bada"],
    "Biriyani": ["biryani", "briyani", "biriyani", "biriani", "buriyani", "buriani"],
    "Chaat": ["chaat", "chat", "chats", "chaats"],
    "Chutney": ["chutney", "chatney", "chatni", "chatniy", "chutni"],
    "Gulab Jamun": ["gulab jamun", "gulab jaman", "gulab jamoon", "gulab jamuns", "gulab jamans", "gulab jamoons", "gulab jamanas", "gulab jamuna"],
    "Jalebi": ["jalebi", "jilbi", "jilipi", "jalibi", "jeri", "jeri sweet", "jilapi"],
    "Kulfi": ["kulfi", "kulphi", "qulfi", "qulphi"],
    "Lassi": ["lassi", "lassie", "lassies", "lassis"],
    "Naan": ["naan", "nan", "nans", "naans"],
    "Pakora": ["pakora", "pakoda", "pakodas", "pakoras"],
    "Raita": ["raita", "raitas"],
    "Roti": ["roti", "roty", "rotis", "roties"],
    "Samosa": ["samosa", "samosa", "samosas", "samoosa", "samoosas"],
    "Tandoori Chicken": ["tandoori chicken", "tandoori chiken", "tandori chicken", "tandori chiken", "tanduri chicken", "tanduri chiken", "tandoori murgh", "tandoori murg", "tandori murgh", "tandori murg", "tanduri murgh", "tanduri murg"],
    "Vindaloo": ["vindaloo", "vindaloo curry", "vindaloo masala", "vindalu", "vindalho", "vindal"],
    "Rasgulla": ["rasgulla", "rasgullas", "rosogolla", "rosogollas"],
    "Gulab Jamun": ["gulab jamun", "gulab jaman", "gulab jamoon", "gulab jamuns", "gulab jamans", "gulab jamoons", "gulab jamanas", "gulab jamuna"],
    "Pani Puri": ["pani puri", "panipuri", "puchka", "gol gappe", "phuchka", "phulki", "pakodi"],
    "Bhindi masala": ["bhindi fry", "bhindi ki sabzi", "okra masala", "okra fry", "okra ki sabzi", "vendakka masala", "vendakka fry", "vendakka curry"],
    "Aloo Gobi": ["aloo gobi", "alu gobi", "aloo gobhi", "alu gobhi", "potato cauliflower curry", "potato cauliflower masala"],
    "Paneer Butter Masala": ["paneer butter masala", "paneer makhani", "paneer makhanwala", "paneer makhanwalla"],
    "Palak Paneer": ["palak paneer", "saag paneer", "spinach paneer"],
    "Chana Masala": ["chana masala", "chole masala", "chana curry", "chole curry", "chickpea curry", "chickpea masala"],
    "Butter Chicken": ["butter chicken", "murgh makhani"],
    "Chicken Tikka Masala": ["chicken tikka masala", "chicken tikka gravy", "chicken tikka curry"],
    "Rogan Josh": ["rogan josh", "rogan ghosht", "roghan josh", "roghan ghosht", "lamb curry", "lamb masala"],
    "Bhuna Gosht": ["bhuna gosht", "bhuna ghosht", "bhuna lamb", "bhuna mutton", "bhuna meat"],
    "Biriyani": ["biryani", "biriyani", "biriani", "buriyani", "buriani", "rice pilaf"],
    "Pulao": ["pulao", "pilaf"],
    "Raita": ["raita", "yogurt salad"],
    "Lassi": ["lassi", "yogurt drink"],
    "Idli": ["idli", "iddly", "idlly", "idly", "Italy", "italy"],
    "Dosa": ["dosa", "dhosai", "thosai", "dosai"],
    "Sambar": ["sambar", "saambar", "sambhar"],
    "Rasam": ["rasam", "saaru"],
    "Vada": ["vada", "wada"],
    "Upma": ["upma", "uppuma", "uppittu"],
    "Pongal": ["pongal", "ponggal", "khara pongal", "ven pongal"],
    "Parotta": ["parotta", "paratha", "barotta"],
    "Biryani": ["biryani", "biriyani", "biriani", "buriyani", "buriani"],
    "Kothu Parotta": ["kothu parotta", "kothu paratha", "chopped parotta"],
    "Sambal": ["sambal", "sambol", "thovaiyal", "chutney"],
    "Thayir Sadam": ["thayir sadam", "curd rice", "yogurt rice"],
    "Poriyal": ["poriyal", "palya", "thoran"],
    "Kuzhambu": ["kuzhambu", "kulambu"],
    "Molagootal": ["molagootal", "molagoottal"],
    "Kootu": ["kootu", "kozhambu"],
    "Avial": ["avial", "aviyal"],
    "Puttu": ["puttu", "pittu"],
    "Appam": ["appam", "appa"],
    "Adai": ["adai", "ada"],
    "Payasam": ["payasam", "payasa", "kheer"],
    "Thosai": ["thosai", "dosai", "dosa"],
    "Bonda": ["bonda", "maddur vada"],
    "Kesari": ["kesari", "kesari bath", "sheera"],
    "Sundal": ["sundal", "guggillu"],
    "Patties": ["patties", "pattis"],
    "Murukku": ["murukku", "chakli"],
    "Thengai Burfi": ["thengai burfi", "coconut burfi"],
    "Sakkarai Pongal": ["sakkarai pongal", "sweet pongal"],
    "Thattai": ["thattai", "thattu vadai"],
    "Seedai": ["seedai", "cheedai"],
    "Kadalai Mittai": ["kadalai mittai", "peanut chikki"],
    "Ribbon Pakoda": ["ribbon pakoda", "othu pakoda"],
    "Mixture": ["mixture", "mix"],
    "Kara Sev": ["kara sev", "khara sev"],
    "Thenkuzhal": ["thenkuzhal", "thenkulal"],
    "Adhirasam": ["adhirasam", "athirasam"],
    "Paniyaram": ["paniyaram", "unniyappam"],
    "Thirunelveli Halwa": ["thirunelveli halwa", "halwa"],
    "Kanchipuram Idli": ["kanchipuram idli", "kancheepuram idli"],
    "Pani Poori": ["pani poori", "pani puri", "gol gappa"],
    "Medhu Vada": ["medhu vada", "medu vada", "ulundhu vadai"],
    "Karupatti Mittai": ["karupatti mittai", "palm jaggery candy"],
    "Mysore Pak": ["mysore pak", "mysuru pak"],
    "Karuvadu": ["karuvadu", "dried fish"],
    "Chettinad Chicken": ["chettinad chicken", "chettinaad chicken"],
    "Fish Curry": ["fish curry", "meen curry"],
    "Mutton Chukka": ["mutton chukka", "lamb chukka"],
    "Kerala Parotta": ["kerala parotta", "malabar paratha"],
    "Uthappam": ["uthappam", "uthappa"],
    "Kara Kuzhambu": ["kara kuzhambu", "spicy kuzhambu"],
    "Chicken 65": ["chicken 65", "spicy chicken fry"],
    "Kalyana Rasam": ["kalyana rasam", "wedding rasam"],
    "Mysore Masala Dosa": ["mysore masala dosa", "mysuru masala dosa"],
    "Arisi Upma": ["arisi upma", "rice upma"],
    "Masala Vadai": ["masala vadai", "masala vada"],
    "Pudina Chutney": ["pudina chutney", "mint chutney"],
    "Idiyappam": ["idiyappam", "string hoppers"],
    "Kambu Koozh": ["kambu koozh", "bajra koozh"],
    "Murungakkai Sambar": ["murungakkai sambar", "drumstick sambar"],
    "Veg Kothu Parotta": ["veg kothu parotta", "vegetable kothu paratha"],
    "Milagu Kuzhambu": ["milagu kuzhambu", "pepper kuzhambu"],
    "Muttai Kulambu": ["muttai kulambu", "egg kulambu"],
    "Onion Pakoda": ["onion pakoda", "vengaya pakoda"],
    "Rava Kesari": ["rava kesari", "semolina kesari"],
    "Thengai Thogayal": ["thengai thogayal", "coconut thuvaiyal"],
    "Vazhaipoo Vadai": ["vazhaipoo vadai", "banana flower vadai"],
    "Keerai Kootu": ["keerai kootu", "spinach kootu"],
    "Mushroom Biryani": ["mushroom biryani", "kadai mushroom biryani"],
    "Paruppu Vadai": ["paruppu vadai", "dal vada"],
    "Ragi Mudde": ["ragi mudde", "finger millet balls"],
    "Sakkaravalli Kizhangu Poriyal": ["sakkaravalli kizhangu poriyal", "sweet potato stir-fry"],
    "Thakkali Rasam": ["thakkali rasam", "tomato rasam"],
    "Ulunthu Vadai": ["ulunthu vadai", "urad dal vada"],
    "Varagu Arisi Sambar Sadam": ["varagu arisi sambar sadam", "kodo millet sambar rice"],
    "Ven Pongal": ["ven pongal", "khara pongal"],
    "Aama Vadai": ["aama vadai", "rajasthani dal vada"],
    "Bisi Bele Bath": ["bisi bele bath", "hot lentil rice"],
    "Curd Rice": ["curd rice", "thayir sadam"],
    "Dosa": ["dosa", "dosai"],
    "Egg Curry": ["egg curry", "muttai kulambu"],
    "Fish Fry": ["fish fry", "meen varuval"],
    "Gobi Manchurian": ["gobi manchurian", "cauliflower manchurian"],
    "Horsegram Rasam": ["horsegram rasam", "kollu rasam"],
    "Idli": ["idli"],
    "Jangiri": ["jangiri", "imarti"],
    "Kadalai Curry": ["kadalai curry", "chana masala"],
    "Lemon Rice": ["lemon rice", "elumichai sadam"],
    "Mango Pickle": ["mango pickle", "mangai oorugai"],
    "Nandu Masala": ["nandu masala", "crab masala"],
    "Onion Uttapam": ["onion uttapam", "onion uthappam"],
    "Pachadi": ["pachadi", "raitha"],
    "Quinoa Biryani": ["quinoa biryani", "indian quinoa biryani"],
    "Rajma Masala": ["rajma masala", "kidney bean masala"],
    "Semiya Payasam": ["semiya payasam", "vermicelli kheer"],
    "Thayir Vadai": ["thayir vadai", "dahi vada"],
    "Uppu Kari": ["uppu kari", "salted and dried fish"],
    "Vada": ["vada", "dal vada"],
    "Wheat Halwa": ["wheat halwa", "atta halwa"],
    "Xacuti Chicken": ["xacuti chicken", "goan chicken xacuti"],
    "Yellow Dal Tadka": ["yellow dal tadka", "moong dal tadka"],
    "Zarda Pulao": ["zarda pulao", "sweet saffron rice"],
    "Adai": ["adai"],
    "Bajji": ["bajji"],
    "Chana Bhatura": ["chana bhatura"],
    "Chappathi": ["chappathi"],
}

def word_change(word1):
    word = word1

    for food, spellings in food_dictionary.items():
        if word.lower() in [s.lower() for s in spellings]:
            corrected_word = food
            break
    else:
        corrected_word = None

    if corrected_word:
        return corrected_word
    else:
        return word1
